services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goldenhive-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
